// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtomasyonApi.Data;

#nullable disable

namespace OtomasyonApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202085020_InitialRebuild")]
    partial class InitialRebuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtomasyonApi.Models.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("carikodu");

                    b.Property<string>("CariTipi")
                        .HasColumnType("text")
                        .HasColumnName("caritipi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean")
                        .HasColumnName("durum");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<string>("Ilce")
                        .HasColumnType("text")
                        .HasColumnName("ilce");

                    b.Property<string>("ParaBirimi")
                        .HasColumnType("text")
                        .HasColumnName("parabirimi");

                    b.Property<string>("Sehir")
                        .HasColumnType("text")
                        .HasColumnName("sehir");

                    b.Property<string>("TcNo")
                        .HasColumnType("text")
                        .HasColumnName("tcno");

                    b.Property<string>("Telefon")
                        .HasColumnType("text")
                        .HasColumnName("telefon");

                    b.Property<string>("Telefon2")
                        .HasColumnType("text")
                        .HasColumnName("telefon2");

                    b.Property<string>("TicariUnvan")
                        .HasColumnType("text")
                        .HasColumnName("ticariunvan");

                    b.Property<string>("Ulke")
                        .HasColumnType("text")
                        .HasColumnName("ulke");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unvan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("text")
                        .HasColumnName("vergidairesi");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text")
                        .HasColumnName("vergino");

                    b.HasKey("Id");

                    b.ToTable("cariler");
                });

            modelBuilder.Entity("OtomasyonApi.Models.CariHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<decimal>("Alacak")
                        .HasColumnType("numeric")
                        .HasColumnName("alacak");

                    b.Property<int?>("BankaId")
                        .HasColumnType("integer")
                        .HasColumnName("bankaid");

                    b.Property<decimal>("Borc")
                        .HasColumnType("numeric")
                        .HasColumnName("borc");

                    b.Property<int>("CariId")
                        .HasColumnType("integer")
                        .HasColumnName("cariid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Doviz")
                        .HasColumnType("text")
                        .HasColumnName("doviz");

                    b.Property<string>("EvrakTipi")
                        .HasColumnType("text")
                        .HasColumnName("evraktipi");

                    b.Property<int?>("KasaId")
                        .HasColumnType("integer")
                        .HasColumnName("kasaid");

                    b.Property<decimal?>("Kur")
                        .HasColumnType("numeric")
                        .HasColumnName("kur");

                    b.Property<int?>("ReferansId")
                        .HasColumnType("integer")
                        .HasColumnName("referansid");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tarih");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.ToTable("carihareketler");
                });

            modelBuilder.Entity("OtomasyonApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OtomasyonApi.Models.CariHareket", b =>
                {
                    b.HasOne("OtomasyonApi.Models.Cari", "Cari")
                        .WithMany("Hareketler")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("OtomasyonApi.Models.Cari", b =>
                {
                    b.Navigation("Hareketler");
                });
#pragma warning restore 612, 618
        }
    }
}
